services:
  - type: web
    name: meetly-backend
    env: node
    plan: free
    region: oregon
    rootDir: ./backend
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    healthCheck:
      path: /health
      initialDelaySeconds: 120
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: meetly-db-credentials
